# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# ariesve. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that ariesve is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.

# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.

DEVICE_PACKAGE_OVERLAYS := device/samsung/ariesve-common/overlay

# kernel modules for ramdisk
RAMDISK_MODULES = $(addprefix device/samsung/galaxysplus/modules/,bthid.ko sec_param.ko)
PRODUCT_COPY_FILES += $(foreach module,\
	$(RAMDISK_MODULES),\
	$(module):root/lib/modules/$(notdir $(module)))

# other kernel modules not in ramdisk
PRODUCT_COPY_FILES += $(foreach module,\
	$(filter-out $(RAMDISK_MODULES),$(wildcard device/samsung/galaxysplus/modules/*.ko)),\
	$(module):system/lib/modules/$(notdir $(module)))

# Kernel
ifeq ($(TARGET_PREBUILT_KERNEL),)
    LOCAL_KERNEL := device/samsung/galaxysplus/kernel
else
    LOCAL_KERNEL := $(TARGET_PREBUILT_KERNEL)
endif

PRODUCT_COPY_FILES += \
    $(LOCAL_KERNEL):kernel

# We want English on top of small_languages
PRODUCT_LOCALES += en_GB
PRODUCT_DEFAULT_LANGUAGE := en_GB

# Screen density is actually considered a locale (since it is taken into account
# the the build-time selection of resources). The product definitions including
# this file must pay attention to the fact that the first entry in the final
# PRODUCT_LOCALES expansion must not be a density.

PRODUCT_LOCALES += hdpi

# Boot screen
PRODUCT_COPY_FILES += \
    device/samsung/galaxysplus/splash/ARIESVE.rle:root/ARIESVE.rle \
    device/samsung/galaxysplus/splash/charging.rle:root/charging.rle \
    device/samsung/galaxysplus/splash/ARIESVE.rle:recovery/ARIESVE.rle \
    device/samsung/galaxysplus/splash/charging.rle:recovery/charging.rle \
    device/samsung/galaxysplus/bootanimation.zip:system/media/bootanimation.zip

# These are the hardware-specific configuration files
PRODUCT_COPY_FILES += \
    device/samsung/galaxysplus/etc/gps.conf:system/etc/gps.conf \
    device/samsung/galaxysplus/etc/wifi.conf:system/etc/wifi/wifi.conf \
    device/samsung/galaxysplus/etc/ts.conf:system/etc/ts.conf
#    device/samsung/galaxysplus/etc/asound.conf:system/etc/asound.conf

# Init files
PRODUCT_COPY_FILES += \
    device/samsung/ariesve-common/init.qcom.rc:root/init.qcom.rc \
    device/samsung/ariesve-common/ueventd.gt-i9001.rc:root/ueventd.gt-i9001.rc \
    device/samsung/ariesve-common/vold.fstab:system/etc/vold.fstab \
    device/samsung/ariesve-common/lpm.rc:root/lpm.rc \
    $(LOCAL_PATH)/recovery/fix_reboot.sh:recovery/root/sbin/fix_reboot.sh \
    device/samsung/galaxysplus/PowerOn.wav:system/etc/PowerOn.wav

# Bluetooth configuration files
PRODUCT_COPY_FILES += \
    system/bluetooth/data/main.conf:system/etc/bluetooth/main.conf \
    vendor/samsung/galaxysplus/proprietary/bin/BCM4329B1_002.002.023.0746.0000_SS_S1-plus-38_4MHz-TEST-ONLY.hcd:system/etc/bluetooth/BCM4329B1_002.002.023.0746.0000_SS_S1-plus-38_4MHz-TEST-ONLY.hcd

# Media configuration xml file
PRODUCT_COPY_FILES += \
    device/samsung/ariesve-common/media_profiles.xml:system/etc/media_profiles.xml

# These are the hardware-specific features
PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
	frameworks/base/data/etc/android.hardware.camera.autofocus.xml:system/etc/permissions/android.hardware.camera.autofocus.xml \
	frameworks/base/data/etc/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml \
	frameworks/base/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
	frameworks/base/data/etc/android.hardware.sensor.light.xml:system/etc/permissions/android.hardware.sensor.light.xml \
	frameworks/base/data/etc/android.hardware.sensor.proximity.xml:system/etc/permissions/android.hardware.sensor.proximity.xml \
	frameworks/base/data/etc/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml \
	frameworks/base/data/etc/android.hardware.touchscreen.multitouch.distinct.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml \
	frameworks/base/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
	frameworks/base/data/etc/android.hardware.touchscreen.multitouch.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.xml \
	frameworks/base/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	frameworks/base/data/etc/android.software.sip.voip.xml:system/etc/permissions/android.software.sip.voip.xml \
	frameworks/base/data/etc/android.software.sip.xml:system/etc/permissions/android.software.sip.xml \
	frameworks/base/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
	packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

# Additional framework
PRODUCT_COPY_FILES += \
    vendor/samsung/galaxysplus/proprietary/framework/seccamera.jar:system/framework/seccamera.jar \
    vendor/samsung/galaxysplus/proprietary/framework/sec_feature.jar:system/framework/sec_feature.jar \
    vendor/samsung/galaxysplus/proprietary/framework/sechardware.jar:system/framework/sechardware.jar

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
    device/samsung/ariesve-common/sec_jack.kl:system/usr/keylayout/sec_jack.kl

# apns config file
PRODUCT_COPY_FILES += \
        vendor/cyanogen/prebuilt/common/etc/apns-conf.xml:system/etc/apns-conf.xml

# Libraries
PRODUCT_PACKAGES += \
    hostap\
    gralloc.msm7k \
    gralloc.default \
    lights.msm7k \
    overlay.default \
    sensors.default \
    libaes \
    libauth \
    libcm \
    libfm_wan_api \
    libfmradio_jni \
    libgenlock \
    libmemalloc \
    libnetmgr \
    libOmxCore \
    libOmxVenc \
    libOmxVdec \
    libOmxAacDec \
    libopencorehw \
    libOpenVG \
    liboverlay \
    libpbmlib \
    libpng \
    libqcomm_omx \
    libQcomUI \
    librs_jni \
    libscreencapture \
    libspeex \
    libspeexresampler \
    libstagefrighthw \
    libtilerenderer \
    libtslib \
    libuim \
    libwms \
    corgi \
    dejitter \
    inputraw \
    linear \
    variance \
    pthres \
    com.android.future.usb.accessory 

PRODUCT_PACKAGES += \
    make_ext4fs

# Service Mode Secret Code
PRODUCT_PACKAGES += \
	SamsungServiceMode

## Live wallpapers
#PRODUCT_PACKAGES += \
#    LiveWallpapers \
#    LiveWallpapersPicker

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
    ro.opengles.version=131072

# For userdebug builds
ADDITIONAL_DEFAULT_PROPERTIES += \
    ro.ril.hsxpa=1 \
    ro.ril.gprsclass=10 \
    ro.secure=0 \
    ro.allow.mock.location=1 \
    ro.debuggable=1

# These are the hardware-specific settings that are stored in system properties.
# Note that the only such settings should be the ones that are too low-level to
# be reachable from resources or other mechanisms.
PRODUCT_PROPERTY_OVERRIDES += \
       wifi.interface=eth0 \
       wifi.supplicant_scan_interval=60 \
       dalvik.vm.heapsize=64m \
       ro.config.ehrpd=true \
       ro.hdmi.enable=true \
       ro.use_data_netmgrd=true \
       mobiledata.interfaces=eth0,gprs,ppp0 \
       debug.sf.hw=1 \
       debug.gr.numframebuffers=1 \
       debug.gr.swapinterval=0 \
       video.accelerate.hw=1 \
       debug.performance.tuning=1 \
       dev.sfbootcomplete=0

# enable Google-specific location features,
# like NetworkLocationProvider and LocationCollector
PRODUCT_PROPERTY_OVERRIDES += \
        ro.com.google.locationfeatures=1 \
        ro.com.google.networklocation=1

# Extended JNI checks
# The extended JNI checks will cause the system to run more slowly, but they can spot a variety of nasty bugs 
# before they have a chance to cause problems.
# Default=true for development builds, set by android buildsystem.
PRODUCT_PROPERTY_OVERRIDES += \
    ro.kernel.android.checkjni=0 \
    dalvik.vm.checkjni=false

# we have enough storage space to hold precise GC data
PRODUCT_TAGS += dalvik.gc.type-precise

# See comment at the top of this file. This is where the other
# half of the device-specific product definition file takes care
# of the aspects that require proprietary drivers that aren't
# commonly available
$(call inherit-product-if-exists, vendor/samsung/galaxysplus/galaxysplus-vendor.mk)
